# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/997968/homebrew/Cellar/cmake/3.25.1/bin/cmake

# The command to remove a file.
RM = /Users/997968/homebrew/Cellar/cmake/3.25.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/997968/lace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/997968/lace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/997968/homebrew/Cellar/cmake/3.25.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/997968/homebrew/Cellar/cmake/3.25.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/997968/lace/CMakeFiles /Users/997968/lace//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/997968/lace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lace

# Build rule for target.
lace: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lace
.PHONY : lace

# fast build rule for target.
lace/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/build
.PHONY : lace/fast

expression.o: expression.cpp.o
.PHONY : expression.o

# target to build an object file
expression.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/expression.cpp.o
.PHONY : expression.cpp.o

expression.i: expression.cpp.i
.PHONY : expression.i

# target to preprocess a source file
expression.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/expression.cpp.i
.PHONY : expression.cpp.i

expression.s: expression.cpp.s
.PHONY : expression.s

# target to generate assembly for a file
expression.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/expression.cpp.s
.PHONY : expression.cpp.s

lace_example.o: lace_example.cpp.o
.PHONY : lace_example.o

# target to build an object file
lace_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/lace_example.cpp.o
.PHONY : lace_example.cpp.o

lace_example.i: lace_example.cpp.i
.PHONY : lace_example.i

# target to preprocess a source file
lace_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/lace_example.cpp.i
.PHONY : lace_example.cpp.i

lace_example.s: lace_example.cpp.s
.PHONY : lace_example.s

# target to generate assembly for a file
lace_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/lace_example.cpp.s
.PHONY : lace_example.cpp.s

lacetypes.o: lacetypes.cpp.o
.PHONY : lacetypes.o

# target to build an object file
lacetypes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/lacetypes.cpp.o
.PHONY : lacetypes.cpp.o

lacetypes.i: lacetypes.cpp.i
.PHONY : lacetypes.i

# target to preprocess a source file
lacetypes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/lacetypes.cpp.i
.PHONY : lacetypes.cpp.i

lacetypes.s: lacetypes.cpp.s
.PHONY : lacetypes.s

# target to generate assembly for a file
lacetypes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/lacetypes.cpp.s
.PHONY : lacetypes.cpp.s

lexer.o: lexer.cpp.o
.PHONY : lexer.o

# target to build an object file
lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/lexer.cpp.o
.PHONY : lexer.cpp.o

lexer.i: lexer.cpp.i
.PHONY : lexer.i

# target to preprocess a source file
lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/lexer.cpp.i
.PHONY : lexer.cpp.i

lexer.s: lexer.cpp.s
.PHONY : lexer.s

# target to generate assembly for a file
lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lace.dir/build.make CMakeFiles/lace.dir/lexer.cpp.s
.PHONY : lexer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lace"
	@echo "... expression.o"
	@echo "... expression.i"
	@echo "... expression.s"
	@echo "... lace_example.o"
	@echo "... lace_example.i"
	@echo "... lace_example.s"
	@echo "... lacetypes.o"
	@echo "... lacetypes.i"
	@echo "... lacetypes.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

